SONG_DIRECTORY = '/media/pi/2E00-9AA8/music/' #'C:/Users/Pietro/Desktop/Feel & Drive/music'
CENTRAL_API = 'http://192.168.0.3:5000/api/v1'
FER_SERVER = 'http://192.168.0.34:5001/fer-server'
PI_BASE_URL = 'localhost'

#Z-wave config
Z_BASE_URL = 'http://localhost:8083'
Z_USERNAME = 'admin'
Z_PASSWORD = 'AmI2019'
DEVICE_URL = Z_BASE_URL + '/ZWaveAPI/Run/devices[{}].instances[{}].commandClasses[{}]'
SWITCH_BINARY = '37'






# HUE LIGHTS
#HUE_BASE_URL = 'http://localhost:80'
HUE_BASE_URL = 'http://192.168.0.201'
# example username, generated by following https://developers.meethue.com/develop/get-started-2/
HUE_USERNAME = "GtmODLN6GK9MXxcoxkvRJuIhQvdjzXSOPW77IRGL"
# if you are using the emulator, the username is:
#HUE_USERNAME = 'newdeveloper'
