SONG_DIRECTORY =  'C:/Users/Pietro/Desktop/Feel & Drive/music/Happiness' #'/media/pi/2E00-9AA8/music/Happiness'
CENTRAL_API = 'http://192.168.1.10:5000/api/v1'
FER_SERVER = 'http://192.168.0.34:5000/fer-server'

# HUE LIGHTS
#HUE_BASE_URL = 'http://localhost:80'
HUE_BASE_URL = 'http://192.168.0.201'
# example username, generated by following https://developers.meethue.com/develop/get-started-2/
HUE_USERNAME = "GtmODLN6GK9MXxcoxkvRJuIhQvdjzXSOPW77IRGL"
# if you are using the emulator, the username is:
#HUE_USERNAME = 'newdeveloper'
